### ISSUE TITLE
Which MPI implementation shoud be used?

### ISSUE THREAD

**Issue by kafkasl** [ishanhan/parallel-implementation-of-kmeans#5]
I plan to use your MPI implementation but I was wondering if I should use:
* mpi_kmeans.py, or
* mpi_kmeans_mod.py

Thanks

**Comment by sidkothiyal** [comment]
Hi @kafkasl 
As you might know when you use MPI, you have to start multiple processes and MPI is used to pass data between them. Processes end up being very heavy (resources wise) and after a point it starts taking a toll on your CPU (This might even lead to your system crashing).

When we tried to make Kmeans parallel using MPI, we initially thought that since the number of points is far greater than the total number of points (mpi_kmeans.py), we will take each point as a separate process and calculate its distance from all the cluster centres and then gather info about the closest cluster centre for each point and then recalculate the cluster centre. When we tried experimenting with huge number of cluster points, our systems started giving up, so we thought of switching to some other implementation.

In the other implementation (mpi_kmeans_mod.py), we used each cluster center as a separate process and calculated its distance from each point. Found the closest cluster centre for each point and recalculated the cluster centre.

So the first implementation is much faster but requires a system with more cores to handle the processing.

**Comment by kafkasl** [comment]
@sidkothiyal thanks for the explanation! Is this implementation is part of any scientific publication?

**Comment by sidkothiyal** [comment]
Unfortunately no. 
It was just something the two of us were messing around with in college. Glad it was helpful to someone
